#!/usr/bin/env python
#

import sys
import re
import giss.modele
import datetime
import os.path

# Usage
if len(sys.argv) == 1 :
	sys.stderr.write('Usage: lsacc <rundeck-dir> [month0 yyyymm] [month1 yyyymm>]\n')
	sys.stderr.write('   Lists the acc files from a ModelE run, in chronological order.')
	sys.stderr.write('   Useful for loading the command lines of other utilities')
	sys.exit(-1)

# Parse arguments
parent_dir, rundeck = os.path.split(sys.argv[1])

# Get the date range we're looking for
monthRE = re.compile('(\d\d\d\d)(\d\d)')
if len(sys.argv) <= 2 :
	month0 = None
else :
	smonth0 = sys.argv[2]
	match = monthRE.match(smonth0)
	month0 = datetime.date(int(match.group(1)), int(match.group(2)), 1)

if len(sys.argv) <= 3 :
	month1 = None
else :
	smonth1 = sys.argv[3]
	match = monthRE.match(smonth1)
	month1 = datetime.date(int(match.group(1)), int(match.group(2)), 1)

#sys.stderr.write('%s %s\n' % (str(month0), str(month1)))

# See what files are out there
acc_files = giss.modele.list_acc_files(os.path.join(parent_dir,rundeck), rundeck,
	date0=month0, date1=month1)

# Filter...
fnames = [x[1] for x in acc_files]

# Output
print '\n'.join(fnames)
