#!/usr/bin/env python
#

import matplotlib
matplotlib.use('GTK3Agg')
#matplotlib.use('module://giss.matplotlib.backend_gtk3xxagg')
# This unfortunately makes mouse tips stop working altogether until a restart of X11.

from pncview.pncview import *
from pncview import gui
from giss import thunkserver
import giss.util as giutil
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk
import sys

#fname = '/Users/rpfische/exp/151014-integrate/build/e4f40-twoway/run05-firstyear/modele_out.nc'
fname = sys.argv[2]
#varmgrs = ['pncview.varmgr.modele.ModelEVarManager']

if True:
	ts = thunkserver.Client(sys.argv[1])
	ts.exec(thunkserver.ImportThunk(['matplotlib.pyplot']))
	ts.exec(giutil.Thunk(ss_init, fname))
	vmgr = ClientVarMgr(ts, 'vmgr')
else:
	vmgr = ModelEVarManager(fname)

mod = gui.PCViewModel(vmgr)
win = gui.PCViewWindow(mod)
win.connect("delete-event", Gtk.main_quit)
win.set_size_request(400,600)
win.show_all()
Gtk.main()

