#!/usr/bin/env python
#

import matplotlib
matplotlib.use('GTK3Agg')
#matplotlib.use('module://giss.matplotlib.backend_gtk3xxagg')
# This unfortunately makes mouse tips stop working altogether until a restart of X11.

from giss.plot.pncview import *
from giss import thunkserver

if True:
	ts = thunkserver.Client()
	ts.exec(giutil.Thunk(ss_init, sys.argv))
	vmgr = ClientVarMgr(ts, 'vmgr')
else:
	fname = '/Users/rpfische/exp/151014-integrate/build/e4f40-twoway/run05-firstyear/modele_out.nc'
	#fname=sys.argv[1]
	vmgr = ModelEVarManager(fname)

mod = PCViewModel(vmgr)
win = PCViewWindow(mod)
win.connect("delete-event", Gtk.main_quit)
win.set_size_request(400,600)
win.show_all()
Gtk.main()

